### ISSUE TITLE
more detail in readme

### ISSUE THREAD

**Issue by amytimed** [Fry98/TheStanleyParableButtonRenamer#1]
does it say it in text to speech? apples? bananas?

**Comment by Fry98** [comment]
Yes, it uses the OS's TTS system through this utility: https://www.elifulkerson.com/projects/commandline-text-to-speech.php

Didn't think implementaion details were that important to mention in the README but I might add them in the future.

**Comment by Fry98** [comment]
Added a "How does it work?" section into the README. That should hopefully clear things up a bit.
